<?php

namespace app\controllers\valiables\locations;

class Wards
{

    public function list(): array
    {
        return [
            "1" => [
                "1" => "port reitz",
                "2" => "kipevu",
                "3" => "airport",
                "4" => "changamwe",
                "5" => "chaani"
            ],
            "2" => [
                "6" => "jomvu kuu",
                "7" => "miritini",
                "8" => "mikindani"
            ],
            "3" => [
                "9" => "mjambere",
                "10" => "junda",
                "11" => "bamburi",
                "12" => "mwakirunge",
                "13" => "mtopanga",
                "14" => "magogoni",
                "15" => "shanzu"
            ],
            "14" => [
                "16" => "frere town",
                "17" => "ziwa la ng'ombe",
                "18" => "mkomani",
                "19" => "kongowea",
                "20" => "kadzandani"
            ],
            "15" => [
                "21" => "mtongwe",
                "22" => "shika adabu",
                "23" => "bofu",
                "24" => "likoni",
                "25" => "timbwani"
            ],
            "16" => [
                "26" => "mji wa kale/makadara",
                "27" => "tudor",
                "28" => "tononoka",
                "29" => "shimanzi/ganjoni",
                "30" => "majengo"
            ],
            "17" => [
                "31" => "gombatobongwe",
                "32" => "ukunda",
                "33" => "kinondo",
                "34" => "ramisi"
            ],
            "18" => [
                "35" => "pongwekikoneni",
                "36" => "dzombo",
                "37" => "mwereni",
                "38" => "vanga"
            ],
            "19" => [
                "39" => "tsimba golini",
                "40" => "waa",
                "41" => "tiwi",
                "42" => "kubo south",
                "43" => "mkongani"
            ],
            "20" => [
                "44" => "nadavaya",
                "45" => "puma",
                "46" => "kinango",
                "47" => "mackinnon-road",
                "48" => "chengoni/samburu",
                "49" => "mwavumbo",
                "50" => "kasemeni"
            ],
            "21" => [
                "51" => "tezo",
                "52" => "sokoni",
                "53" => "kibarani",
                "54" => "dabaso",
                "55" => "matsangoni",
                "56" => "watamu",
                "57" => "mnarani",
                "58" => "junju",
                "59" => "mwarakaya",
                "60" => "shimo la tewa",
                "61" => "chasimba",
                "62" => "mtepeni"
            ],
            "22" => [
                "63" => "mariakani",
                "64" => "kayafungo",
                "65" => "kaloleni",
                "66" => "mwanamwinga"
            ],
            "23" => [
                "67" => "mwawesa",
                "68" => "ruruma",
                "69" => "kambe/ribe",
                "70" => "rabai/kisurutini"
            ],
            "24" => [
                "71" => "ganze",
                "72" => "bamba",
                "73" => "jaribuni",
                "74" => "sokoke"
            ],
            "25" => [
                "75" => "jilore",
                "76" => "kakuyuni",
                "77" => "ganda",
                "78" => "malindi town",
                "79" => "shella"
            ],
            "26" => [
                "80" => "marafa",
                "81" => "magarini",
                "82" => "gongoni",
                "83" => "adu",
                "84" => "garashi",
                "85" => "sabaki"
            ],
            "27" => [
                "86" => "kipini east",
                "87" => "garsen south",
                "88" => "kipini west",
                "89" => "garsen central",
                "90" => "garsen west",
                "91" => "garsen north"
            ],
            "28" => [
                "92" => "kinakomba",
                "93" => "mikinduni",
                "94" => "chewani",
                "95" => "wayu"
            ],
            "29" => [
                "96" => "chewele",
                "97" => "bura",
                "98" => "bangale",
                "99" => "sala",
                "100" => "madogo"
            ],
            "30" => [
                "101" => "faza",
                "102" => "kiunga",
                "103" => "basuba",
                "104" => "shella",
                "105" => "mkomani",
                "106" => "hindi",
                "107" => "mkunumbi",
                "108" => "hongwe",
                "109" => "witu",
                "110" => "bahari"
            ],
            "31" => [
                "111" => "chala",
                "112" => "mahoo",
                "113" => "bomeni",
                "114" => "mboghoni",
                "115" => "mata"
            ],
            "32" => [
                "116" => "wundanyi/mbale",
                "117" => "werugha",
                "118" => "wumingu/kishushe",
                "119" => "mwanda/mgange"
            ],
            "33" => [
                "120" => "rong'e",
                "121" => "mwatate",
                "122" => "bura",
                "123" => "chawia",
                "124" => "wusi/kishamba"
            ],
            "34" => [
                "125" => "mbololo",
                "126" => "sagalla",
                "127" => "kaloleni",
                "128" => "marungu",
                "129" => "kasigau",
                "130" => "ngolia"
            ],
            "35" => [
                "131" => "waberi",
                "132" => "galbet",
                "133" => "township",
                "134" => "iftin"
            ],
            "36" => [
                "135" => "balambala",
                "136" => "danyere",
                "137" => "jara jara",
                "138" => "saka",
                "139" => "sankuri"
            ],
            "37" => [
                "140" => "modogashe",
                "141" => "benane",
                "142" => "goreale",
                "143" => "maalimin",
                "144" => "sabena",
                "145" => "baraki"
            ],
            "38" => [
                "146" => "dertu",
                "147" => "dadaab",
                "148" => "labasigale",
                "149" => "damajale",
                "150" => "liboi",
                "151" => "abakaile"
            ],
            "39" => [
                "152" => "bura",
                "153" => "dekaharia",
                "154" => "jarajila",
                "155" => "fafi",
                "156" => "nanighi"
            ],
            "40" => [
                "157" => "hulugho",
                "158" => "sangailu",
                "159" => "ijara",
                "160" => "masalani"
            ],
            "41" => [
                "161" => "gurar",
                "162" => "bute",
                "163" => "korondile",
                "164" => "malkagufu",
                "165" => "batalu",
                "166" => "danaba",
                "167" => "godoma"
            ],
            "42" => [
                "168" => "wagberi",
                "169" => "township",
                "170" => "barwago",
                "171" => "khorof/harar"
            ],
            "43" => [
                "172" => "elben",
                "173" => "sarman",
                "174" => "tarbaj",
                "175" => "wargadud"
            ],
            "44" => [
                "176" => "arbajahan",
                "177" => "hadado/athibohol",
                "178" => "ademasajide",
                "179" => "wagalla/ganyure"
            ],
            "45" => [
                "180" => "eldas",
                "181" => "della",
                "182" => "lakoley south/basir",
                "183" => "elnur/tula tula"
            ],
            "46" => [
                "184" => "benane",
                "185" => "burder",
                "186" => "dadaja bulla",
                "187" => "habasswein",
                "188" => "lagboghol south",
                "189" => "ibrahim ure",
                "190" => "diif"
            ],
            "47" => [
                "191" => "takaba south",
                "192" => "takaba",
                "193" => "lag sure",
                "194" => "dandu",
                "195" => "gither"
            ],
            "48" => [
                "196" => "banissa",
                "197" => "derkhale",
                "198" => "guba",
                "199" => "malkamari",
                "200" => "kiliwehiri"
            ],
            "49" => [
                "201" => "ashabito",
                "202" => "guticha",
                "203" => "morothile",
                "204" => "rhamu",
                "205" => "rhamu-dimtu"
            ],
            "50" => [
                "206" => "wargudud",
                "207" => "kutulo",
                "208" => "elwak south",
                "209" => "elwak north",
                "210" => "shimbir fatuma"
            ],
            "51" => [
                "211" => "arabia",
                "212" => "bulla mpya",
                "213" => "khalalio",
                "214" => "neboi",
                "215" => "township"
            ],
            "52" => [
                "216" => "libehia",
                "217" => "fino",
                "218" => "lafey",
                "219" => "warankara",
                "220" => "alungo gof"
            ],
            "53" => [
                "221" => "butiye",
                "222" => "sololo",
                "223" => "heilu-man",
                "224" => "golbo",
                "225" => "moyale township",
                "226" => "uran",
                "227" => "obbu"
            ],
            "54" => [
                "228" => "illeret",
                "229" => "north horr",
                "230" => "dukana",
                "231" => "maikona",
                "232" => "turbi"
            ],
            "55" => [
                "233" => "sagante/jaldesa",
                "234" => "karare",
                "235" => "marsabit central"
            ],
            "56" => [
                "236" => "loiyangalani",
                "237" => "kargi/south horr",
                "238" => "korr/ngurunit",
                "239" => "log logo",
                "240" => "laisamis"
            ],
            "57" => [
                "241" => "wabera",
                "242" => "bulla pesa",
                "243" => "chari",
                "244" => "cherab",
                "245" => "ngare mara",
                "246" => "burat",
                "247" => "oldonyiro",
            ],
            "58" => [
                "248" => "garbatulla",
                "249" => "kinna",
                "250" => "sericho",
                "251" => "maua",
                "252" => "kiegoi/antubochiu",
                "253" => "athiru gaiti",
                "254" => "akachiu",
                "255" => "kanuni"
            ],
            "59" => [
                "256" => "akirang'ondu",
                "257" => "athiru ruujine",
                "258" => "igembe east",
                "259" => "njia",
                "260" => "kangeta"
            ],
            "60" => [
                "261" => "antuambui",
                "262" => "ntunene",
                "263" => "antubetwe kiongo",
                "264" => "naathu",
                "265" => "amwathi"
            ],
            "61" => [
                "266" => "athwana",
                "267" => "akithii",
                "268" => "kianjai",
                "269" => "nkomo",
                "270" => "mbeu"
            ],
            "62" => [
                "271" => "thangatha",
                "272" => "mikinduri",
                "273" => "kiguchwa",
                "274" => "muthara",
                "275" => "karama"
            ],
            "63" => [
                "276" => "municipality",
                "277" => "ntima east",
                "278" => "ntima west",
                "279" => "nyaki west",
                "280" => "nyaki east"
            ],
            "64" => [
                "281" => "timau",
                "282" => "kisima",
                "283" => "kiirua/naari",
                "284" => "ruiri/rwarera",
                "285" => "kibirichia"
            ],
            "65" => [
                "286" => "mwanganthia",
                "287" => "abothuguchi central",
                "288" => "abothuguchi west",
                "289" => "kiagu"
            ],
            "66" => [
                "290" => "mitunguu",
                "291" => "igoji east",
                "292" => "igoji west",
                "293" => "abogeta east",
                "294" => "abogeta west",
                "295" => "nkuene"
            ],
            "67" => [
                "296" => "mitheru",
                "297" => "muthambi",
                "298" => "mwimbi",
                "299" => "ganga",
                "300" => "chogoria"
            ],
            "68" => [
                "301" => "mariani",
                "302" => "karingani",
                "303" => "magumoni",
                "304" => "mugwe",
                "305" => "igambang'ombe"
            ],
            "69" => [
                "306" => "gatunga",
                "307" => "mukothima",
                "308" => "nkondi",
                "309" => "chiakariga",
                "310" => "marimanti"
            ],
            "70" => [
                "311" => "ruguru/ngandori",
                "312" => "kithimu",
                "313" => "nginda",
                "314" => "mbeti north",
                "315" => "kirimari",
                "316" => "gaturi south"
            ],
            "71" => [
                "317" => "gaturi north",
                "318" => "kagaari south",
                "319" => "central  ward",
                "320" => "kagaari north",
                "321" => "kyeni north",
                "322" => "kyeni south"
            ],
            "72" => [
                "323" => "mwea",
                "324" => "makima",
                "325" => "mbeti south",
                "326" => "mavuria",
                "327" => "kiambere"
            ],
            "73" => [
                "328" => "nthawa",
                "329" => "muminji",
                "330" => "evurore"
            ],
            "74" => [
                "331" => "ngomeni",
                "332" => "kyuso",
                "333" => "mumoni",
                "334" => "tseikuru",
                "335" => "tharaka",
            ],
            "75" => [
                "336" => "kyome/thaana",
                "337" => "nguutani",
                "338" => "migwani",
                "339" => "kiomo/kyethani",
            ],
            "76" => [
                "340" => "central",
                "341" => "kivou",
                "342" => "nguni",
                "343" => "nuu",
                "344" => "mui",
                "345" => "waita",
            ],
            "77" => [
                "346" => "mutonguni",
                "347" => "kauwi",
                "348" => "matinyani",
                "349" => "kwa mutonga/kithumula",
            ],
            "78" => [
                "350" => "kisasi",
                "351" => "mbitini",
                "352" => "kwavonza/",
                "353" => "kanyangi",
            ],
            "79" => [
                "354" => "miambani",
                "355" => "township",
                "356" => "kyangwithya west",
                "357" => "mulango",
                "358" => "kyangwithya east",
            ],
            "80" => [
                "359" => "zombe/mwitika",
                "360" => "chuluni",
                "361" => "nzambani",
                "362" => "voo/kyamatu",
                "363" => "endau/malalani",
                "364" => "mutito/kaliku",
            ],
            "81" => [
                "365" => "ikanga/kyatune",
                "366" => "mutomo",
                "367" => "mutha",
                "368" => "ikutha",
                "369" => "kanziko",
                "370" => "athi",
            ],
            "82" => [
                "371" => "kivaa",
                "372" => " central",
                "373" => "ekalakala",
                "374" => "muthesya",
                "375" => "ndithini",
            ],
            "83" => [
                "376" => "ndalani",
                "377" => "matuu",
                "378" => "kithimani",
                "379" => "ikombe",
                "380" => "katangi",
            ],
            "84" => [
                "381" => "kangundo north",
                "382" => "kangundo central",
                "383" => "kangundo east",
                "384" => "kangundo west",
            ],
            "85" => [
                "385" => "tala",
                "386" => "matungulu north",
                "387" => "matungulu east",
                "388" => "matungulu west",
                "389" => "kyeleni",
            ],
            "86" => [
                "390" => "mitaboni",
                "391" => "kathiani central",
                "392" => "upper kaewa/iveti",
                "393" => "lower kaewa/kaani",
            ],
            "87" => [
                "394" => "athi river",
                "395" => "kinanie",
                "396" => "muthwani",
                "397" => "syokimau/mulolongo",
            ],
            "88" => [
                "398" => "kalama",
                "399" => "mua",
                "400" => "mutituni",
                "401" => "machakos central",
                "402" => "mumbuni north",
                "403" => "muvuti/kiima-kimwe",
                "404" => "kola",
            ],
            "89" => [
                "405" => "mbiuni",
                "406" => "makutano/ mwala",
                "407" => "masii",
                "408" => "muthetheni",
                "409" => "wamunyu",
                "410" => "kibauni",
            ],
            "90" => [
                "411" => "tulimani",
                "412" => "mbooni",
                "413" => "kithungo/kitundu",
                "414" => "kisau/kiteta",
                "415" => "waia/kako",
                "416" => "kalawa",
            ],
            "91" => [
                "417" => "kasikeu",
                "418" => "mukaa",
                "419" => "kiima kiu/kalanzoni",
            ],
            "92" => [
                "420" => "ukia",
                "421" => "kee",
                "422" => "kilungu",
                "423" => "ilima",
            ],
            "93" => [
                "424" => "wote",
                "425" => "muvau/kikuumini",
                "426" => "mavindini",
                "427" => "kitise/kithuki",
                "428" => "kathonzweni",
                "429" => "nzaui/kilili/kalamba",
                "430" => "mbitini",
            ],
            "94" => [
                "431" => "makindu",
                "432" => "nguumo",
                "433" => "kikumbulyu north",
                "434" => "kikumbulyu south",
                "435" => "nguu/masumba",
                "436" => "emali/mulala",
            ],
            "95" => [
                "437" => "masongaleni",
                "438" => "mtito andei",
                "439" => "thange",
                "440" => "ivingoni/nzambani",
            ],
            "96" => [
                "441" => "engineer",
                "442" => "gathara",
                "443" => "north kinangop",
                "444" => "murungaru",
                "445" => "njabini\\kiburu",
                "446" => "nyakio",
                "447" => "githabai",
                "448" => "magumu",
            ],
            "97" => [
                "449" => "wanjohi",
                "450" => "kipipiri",
                "451" => "geta",
                "452" => "githioro",
            ],
            "98" => [
                "453" => "karau",
                "454" => "kanjuiri ridge",
                "455" => "mirangine",
                "456" => "kaimbaga",
                "457" => "rurii",
            ],
            "99" => [
                "458" => "gathanji",
                "459" => "gatimu",
                "460" => "weru",
                "461" => "charagita",
            ],
            "100" => [
                "462" => "leshau pondo",
                "463" => "kiriita",
                "464" => "central",
                "465" => "shamata",
            ],
            "101" => [
                "466" => "dedan kimanthi",
                "467" => "wamagana",
                "468" => "aguthi/gaaki",
            ],
            "102" => [
                "469" => "mweiga",
                "470" => "naromoru kiamathaga",
                "471" => "mwiyogo/endarasha",
                "472" => "mugunda",
                "473" => "gatarakwa",
                "474" => "thegu river",
                "475" => "kabaru",
                "476" => "gakawa",
            ],
            "103" => [
                "477" => "ruguru",
                "478" => "magutu",
                "479" => "iriaini",
                "480" => "konyu",
                "481" => "kirimukuyu",
                "482" => "karatina town",
            ],
            "104" => [
                "483" => "mahiga",
                "484" => "iria-ini",
                "485" => "chinga",
                "486" => "karima",
            ],
            "105" => [
                "487" => "gikondi",
                "488" => "rugi",
                "489" => "mukurwe-ini west",
                "490" => "mukurwe-ini central",
            ],
            "106" => [
                "491" => "kiganjo/mathari",
                "492" => "rware",
                "493" => "gatitu/muruguru",
                "494" => "ruring'u",
                "495" => "kamakwa/mukaro",
            ],
            "107" => [
                "496" => "mutithi",
                "497" => "kangai",
                "498" => "thiba",
                "499" => "wamumu",
                "500" => "nyangati",
                "501" => "murinduko",
                "502" => "gathigiriri",
                "503" => "tebere",
            ],
            "108" => [
                "505" => "kabare",
                "506" => "baragwi",
                "507" => "njukiini",
                "508" => "ngariama",
                "509" => "karumandi",
            ],
            "109" => [
                "510" => "mukure",
                "511" => "kiine",
                "512" => "kariti",
            ],
            "110" => [
                "513" => "mutira",
                "514" => "kanyeki-ini",
                "515" => "kerugoya",
                "516" => "inoi",
            ],
            "111" => [
                "517" => "kanyenyaini",
                "518" => "muguru",
                "519" => "rwathia",
            ],
            "112" => [
                "520" => "gitugi",
                "521" => "kiru",
                "522" => "kamacharia",
            ],
            "113" => [
                "523" => "wangu",
                "524" => "mugoiri",
                "525" => "mbiri",
                "526" => "township",
                "527" => "murarandia",
                "528" => "gaturi",
            ],
            "114" => [
                "529" => "kahumbu",
                "530" => "muthithi",
                "531" => "kigumo",
                "532" => "kangari",
                "533" => "kinyona",
            ],
            "115" => [
                "534" => "kimorori/wempa",
                "535" => "makuyu",
                "536" => "kambiti",
                "537" => "kamahuha",
                "538" => "ichagaki",
                "539" => "nginda",
            ],
            "116" => [
                "540" => "ng'araria",
                "541" => "muruka",
                "542" => "kagundu-ini",
                "543" => "gaichanjiru",
                "544" => "ithiru",
                "545" => "ruchu",
            ],
            "117" => [
                "546" => "ithanga",
                "547" => "kakuzi/mitubiri",
                "548" => "mugumo-ini",
                "549" => "kihumbu-ini",
                "550" => "gatanga",
                "551" => "kariara",
            ],
            "118" => [
                "552" => "kiamwangi",
                "553" => "kiganjo",
                "554" => "ndarugu",
                "555" => "ngenda",
            ],
            "119" => [
                "556" => "gituamba",
                "557" => "githobokoni",
                "558" => "chania",
                "559" => "mang'u",
            ],
            "120" => [
                "560" => "murera",
                "561" => "theta",
                "562" => "juja",
                "563" => "witeithie",
                "564" => "kalimoni",
            ],
            "121" => [
                "565" => "township",
                "566" => "kamenu",
                "567" => "hospital",
                "568" => "gatuanyaga",
                "569" => "ngoliba",
            ],
            "122" => [
                "570" => "gitothua",
                "571" => "biashara",
                "572" => "gatongora",
                "573" => "kahawa sukari",
                "574" => "kahawa wendani",
                "575" => "kiuu",
                "576" => "mwiki",
                "577" => "mwihoko",
            ],
            "123" => [
                "578" => "githunguri",
                "579" => "githiga",
                "580" => "ikinu",
                "581" => "ngewa",
                "582" => "komothai",
            ],
            "124" => [
                "583" => "ting'ang'a",
                "584" => "ndumberi",
                "585" => "riabai",
                "586" => "township",
                "587" => "cianda",
                "588" => "karuri",
                "589" => "ndenderu",
                "590" => "muchatha",
                "591" => "kihara",
            ],
            "125" => [
                "592" => "gitaru",
                "593" => "muguga",
                "594" => "nyadhuna",
                "595" => "kabete",
                "596" => "uthiru",
            ],
            "125" => [
                "597" => "karai",
                "598" => "nachu",
                "599" => "sigona",
                "600" => "kikuyu",
                "601" => "kinoo",
            ],
            "126" => [
                "602" => "bibirioni",
                "603" => "limuru central",
                "604" => "ndeiya",
                "605" => "limuru east",
                "606" => "ngecha tigoni",
            ],
            "127" => [
                "607" => "kinale",
                "608" => "kijabe",
                "609" => "nyanduma",
                "610" => "kamburu",
                "611" => "lari/kirenga",
            ],
            "128" => [
                "612" => "kaeris",
                "613" => "lake zone",
                "614" => "lapur",
                "615" => "kaaleng/kaikor",
                "616" => "kibish",
                "617" => "nakalale",
            ],
            "129" => [
                "618" => "kakuma",
                "619" => "lopur",
                "620" => "letea",
                "621" => "songot",
                "622" => "kalobeyei",
                "623" => "lokichoggio",
                "624" => "nanaam",
            ],
            "130" => [
                "625" => "kerio delta",
                "626" => "kang'atotha",
                "627" => "kalokol",
                "628" => "lodwar township",
                "629" => "kanamkemer",
            ],
            "131" => [
                "630" => "kotaruk/lobei",
                "631" => "turkwel",
                "632" => "loima",
                "633" => "lokiriama/lorengippi",
            ],
            "132" => [
                "634" => "kaputir",
                "635" => "katilu",
                "636" => "lobokat",
                "637" => "kalapata",
                "638" => "lokichar",
            ],
            "133" => [
                "639" => "kapedo/napeitom",
                "640" => "katilia",
                "641" => "lokori/kochodin",
            ],
            "134" => [
                "642" => "riwo",
                "643" => "kapenguria",
                "645" => "mnagei",
                "646" => "siyoi",
                "647" => "endugh",
                "648" => "sook",
            ],
            "135" => [
                "649" => "sekerr",
                "650" => "masool",
                "651" => "lomut",
                "652" => "weiwei",
            ],
            "136" => [
                "653" => "suam",
                "654" => "kodich",
                "655" => "kapckok",
                "656" => "kasei",
                "657" => "kiwawa",
                "658" => "alale",
            ],
            "137" => [
                "659" => "chepareria",
                "660" => "batei",
                "661" => "lelan",
                "662" => "tapach",
            ],
            "138" => [
                "663" => "lodokejek",
                "664" => "suguta marmar",
                "665" => "maralal",
                "666" => "loosuk",
                "667" => "poro",
            ],
            "139" => [
                "668" => "el-barta",
                "669" => "nachola",
                "670" => "ndoto",
                "671" => "nyiro",
                "672" => "angata nanyokie",
                "673" => "baawa",
            ],
            "140" => [
                "674" => "waso",
                "675" => "wamba west",
                "676" => "wamba east",
                "677" => "wamba north",
            ],
            "141" => [
                "678" => "kapomboi",
                "679" => "kwanza",
                "680" => "keiyo",
                "681" => "bidii",
            ],
            "142" => [
                "682" => "chepchoina",
                "683" => "endebess",
                "684" => "matumbei",
            ],
            "143" => [
                "685" => "kinyoro",
                "686" => "matisi",
                "687" => "tuwani",
                "689" => "saboti",
                "690" => "machewa",
            ],
            "144" => [
                "691" => "kiminini",
                "692" => "waitaluk",
                "693" => "sirende",
                "694" => "hospital",
                "695" => "sikhendu",
                "696" => "nabiswa",
            ],
            "145" => [
                "697" => "sinyerere",
                "698" => "makutano",
                "699" => "kaplamai",
                "700" => "motosiet",
                "701" => "cherangany/suwerwa",
                "702" => "chepsiro/kiptoror",
                "703" => "sitatunga",
            ],
            "146" => [
                "704" => "moi's bridge",
                "705" => "kapkures",
                "706" => "ziwa",
                "707" => "segero/barsombe",
                "708" => "kipsomba",
                "709" => "soy",
                "710" => "kuinet/kapsuswa",
            ],
            "147" => [
                "711" => "ngenyilel",
                "712" => "tapsagoi",
                "713" => "kamagut",
                "714" => "kiplombe",
                "715" => "kapsaos",
                "716" => "huruma",
            ],
            "148" => [
                "717" => "tembelio",
                "718" => "sergoit",
                "719" => "karuna/meibeki",
                "720" => "moiben",
                "721" => "kimumu",
            ],
            "149" => [
                "722" => "kapsoya",
                "723" => "kaptagat",
                "724" => "ainabkoi/olare",
            ],
            "150" => [
                "725" => "simat/kapseret",
                "726" => "kipkenyo",
                "727" => "ngeria",
                "728" => "megun",
                "729" => "langas",
            ],
            "151" => [
                "730" => "racecourse",
                "731" => "cheptiret/kipchamo",
                "732" => "tulwet/chuiyat",
                "733" => "tarakwa",
            ],
            "152" => [
                "734" => "kapyego",
                "735" => "sambirir",
                "736" => "endo",
                "737" => "embobut / embulot",
            ],
            "153" => [
                "738" => "lelan",
                "739" => "sengwer",
                "740" => "cherang'any/chebororwa",
                "741" => "moiben/kuserwo",
                "742" => "kapsowar",
                "743" => "arror",
            ],
            "154" => [
                "744" => "emsoo",
                "745" => "kamariny",
                "746" => "kapchemutwa",
                "747" => "tambach",
            ],
            "155" => [
                "748" => "kaptarakwa",
                "749" => "chepkorio",
                "750" => "soy north",
                "751" => "soy south",
                "752" => "kabiemit",
                "753" => "metkei",
            ],
            "156" => [
                "754" => "songhor/soba",
                "755" => "tindiret",
                "756" => "chemelil/chemase",
                "757" => "kapsimotwo",
            ],
            "157" => [
                "758" => "kabwareng",
                "759" => "terik",
                "760" => "kemeloi-maraba",
                "761" => "kobujoi",
                "762" => "kaptumo-kaboi",
                "763" => "koyo-ndurio",
            ],
            "158" => [
                "764" => "nandi hills",
                "765" => "chepkunyuk",
                "766" => "ol'lessos",
                "767" => "kapchorua",
            ],
            "159" => [
                "768" => "chemundu/kapng'etuny",
                "769" => "kosirai",
                "770" => "lelmokwo/ngechek",
                "771" => "kaptel/kamoiywo",
                "772" => "kiptuya",
            ],
            "160" => [
                "773" => "chepkumia",
                "774" => "kapkangani",
                "775" => "kapsabet",
                "776" => "kilibwoni",
            ],
            "161" => [
                "777" => "chepterwai",
                "778" => "kipkaren",
                "779" => "kurgung/surungai",
                "780" => "kabiyet",
                "781" => "ndalat",
                "782" => "kabisaga",
                "783" => "sangalo/kebulonik",
            ],
            "162" => [
                "784" => "tirioko",
                "785" => "kolowa",
                "786" => "ribkwo",
                "787" => "silale",
                "788" => "loiyamorock",
                "789" => "tangulbei/korossi",
                "790" => "churo/amaya",
            ],
            "163" => [
                "791" => "barwessa",
                "792" => "kabartonjo",
                "793" => "saimo/kipsaraman",
                "794" => "saimo/soi",
                "795" => "bartabwa",
            ],
            "164" => [
                "796" => "kabarnet",
                "797" => "sacho",
                "798" => "tenges",
                "799" => "ewalel chapchap",
                "800" => "kapropita",
            ],
            "165" => [
                "801" => "marigat",
                "802" => "ilchamus",
                "803" => "mochongoi",
                "804" => "mukutani",
            ],
            "166" => [
                "805" => "mogotio",
                "806" => "emining",
                "807" => "kisanana",
            ],
            "167" => [
                "808" => "lembus",
                "809" => "lembus kwen",
                "810" => "ravine",
                "811" => "mumberes/maji mazuri",
                "812" => "lembus/perkerra",
                "813" => "koibatek",
            ],
            "168" => [
                "814" => "olmoran",
                "815" => "rumuruti township",
                "816" => "kinamba",
                "817" => "marmanet",
                "818" => "igwamiti",
                "819" => "salama",
            ],
            "169" => [
                "820" => "ngobit",
                "821" => "tigithi",
                "822" => "thingithu",
                "823" => "nanyuki",
                "824" => "umande",
            ],
            "170" => [
                "825" => "sosian",
                "826" => "segera",
                "827" => "mukogondo west",
                "828" => "mukogondo east",
            ],
            "171" => [
                "829" => "mariashoni",
                "830" => "elburgon",
                "831" => "turi",
                "832" => "molo",
            ],
            "172" => [
                "833" => "maunarok",
                "834" => "mauche",
                "835" => "kihingo",
                "836" => "nessuit",
                "837" => "lare",
                "838" => "njoro",
            ],
            "173" => [
                "839" => "biashara",
                "840" => "hells gate",
                "841" => "lakeview",
                "842" => "maai-mahiu",
                "843" => "maiella",
                "844" => "olkaria",
                "845" => "naivasha east",
                "846" => "viwandani",
            ],
            "174" => [
                "847" => "gilgil",
                "848" => "elementaita",
                "849" => "mbaruk/eburu",
                "850" => "malewa west",
                "851" => "murindati",
            ],
            "175" => [
                "852" => "amalo",
                "853" => "keringet",
                "854" => "kiptagich",
                "855" => "tinet",
            ],
            "176" => [
                "856" => "kiptororo",
                "857" => "nyota",
                "858" => "sirikwa",
                "859" => "kamara",
            ],
            "177" => [
                "860" => "subukia",
                "861" => "waseges",
                "862" => "kabazi",
            ],
            "178" => [
                "863" => "menengai west",
                "864" => "soin",
                "865" => "visoi",
                "866" => "mosop",
                "867" => "solai",
            ],
            "179" => [
                "868" => "dundori",
                "869" => "kabatini",
                "870" => "kiamaina",
                "871" => "lanet/umoja",
                "872" => "bahati",
            ],
            "180" => [
                "873" => "barut",
                "874" => "london",
                "875" => "kaptembwo",
                "876" => "kapkures",
                "877" => "rhoda",
                "878" => "shaabab",
            ],
            "181" => [
                "879" => "biashara",
                "880" => "kivumbini",
                "881" => "flamingo",
                "882" => "menengai",
                "883" => "nakuru east",
            ],
            "182" => [
                "884" => "kilgoris central",
                "885" => "keyian",
                "886" => "angata barikoi",
                "887" => "shankoe",
                "888" => "kimintet",
                "889" => "lolgorian",
            ],
            "183" => [
                "890" => "ilkerin",
                "891" => "ololmasani",
                "892" => "mogondo",
                "893" => "kapsasian",
            ],
            "184" => [
                "894" => "olpusimoru",
                "895" => "olokurto",
                "896" => "narok town",
                "897" => "nkareta",
                "898" => "olorropil",
                "899" => "melili",
            ],
            "185" => [
                "900" => "mosiro",
                "901" => "ildamat",
                "902" => "keekonyokie",
                "903" => "suswa",
            ],
            "186" => [
                "904" => "majimoto/naroosura",
                "905" => "ololulung'a",
                "906" => "melelo",
                "907" => "loita",
                "908" => "sogoo",
                "909" => "sagamian",
            ],
            "187" => [
                "910" => "ilmotiok",
                "911" => "mara",
                "912" => "siana",
                "913" => "naikarra",
            ],
            "188" => [
                "914" => "olkeri",
                "915" => "ongata rongai",
                "916" => "nkaimurunya",
                "917" => "oloolua",
                "918" => "ngong",
            ],
            "189" => [
                "919" => "purko",
                "920" => "ildamat",
                "921" => "dalalekutuk",
                "922" => "matapato north",
                "923" => "matapato south",
            ],
            "190" => [
                "924" => "kaputiei north",
                "925" => "kitengela",
                "926" => "oloosirkon/sholinke",
                "927" => "kenyawa-poka",
                "928" => "imaroro",
            ],
            "191" => [
                "929" => "keekonyokie",
                "930" => "iloodokilani",
                "931" => "magadi",
                "932" => "ewuaso oonkidong'i",
                "933" => "mosiro",
            ],
            "192" => [
                "934" => "entonet/lenkisim",
                "935" => "mbirikani/eselenkei",
                "936" => "kuku",
                "937" => "rombo",
                "938" => "kimana",
            ],
            "193" => [
                "939" => "londiani",
                "940" => "kedowa/kimugul",
                "941" => "chepseon",
                "942" => "tendeno/sorget",
            ],
            "194" => [
                "943" => "kunyak",
                "944" => "kamasian",
                "945" => "kipkelion",
                "946" => "chilchila",
            ],
            "195" => [
                "947" => "kapsoit",
                "948" => "ainamoi",
                "949" => "kapkugerwet",
                "950" => "kipchebor",
                "951" => "kipchimchim",
                "952" => "kapsaos",
            ],
            "196" => [
                "953" => "kisiara",
                "954" => "tebesonik",
                "955" => "cheboin",
                "956" => "chemosot",
                "957" => "litein",
                "958" => "cheplanget",
                "959" => "kapkatet",
            ],
            "197" => [
                "960" => "waldai",
                "961" => "kabianga",
                "962" => "cheptororiet/seretut",
                "963" => "chaik",
                "964" => "kapsuser",
            ],
            "198" => [
                "965" => "sigowet",
                "966" => "kaplelartet",
                "967" => "soliat",
                "968" => "soin",
            ],
            "199" => [
                "969" => "ndanai/abosi",
                "970" => "chemagel",
                "971" => "kipsonoi",
                "972" => "kapletundo",
                "973" => "rongena/manaret",
            ],
            "200" => [
                "974" => "kong'asis",
                "975" => "nyangores",
                "976" => "sigor",
                "977" => "chebunyo",
                "978" => "siongiroi",
            ],
            "201" => [
                "979" => "merigi",
                "980" => "kembu",
                "981" => "longisa",
                "982" => "kipreres",
                "983" => "chemaner",
            ],
            "202" => [
                "984" => "silibwet township",
                "985" => "ndaraweta",
                "986" => "singorwet",
                "987" => "chesoen",
                "988" => "mutarakwa",
            ],
            "203" => [
                "989" => "chepchabas",
                "990" => "kimulot",
                "991" => "mogogosiek",
                "992" => "boito",
                "993" => "embomos",
            ],
            "204" => [
                "994" => "mautuma",
                "995" => "lugari",
                "996" => "lumakanda",
                "997" => "chekalini",
                "998" => "chevaywa",
                "999" => "lwandeti",
            ],
            "205" => [
                "1000" => "likuyani",
                "1001" => "sango",
                "1002" => "kongoni",
                "1003" => "nzoia",
                "1004" => "sinoko",
            ],
            "206" => [
                "1005" => "west kabras",
                "1006" => "chemuche",
                "1007" => "east kabras",
                "1008" => "butali/chegulo",
                "1009" => "manda-shivanga",
                "1010" => "shirugu-mugai",
                "1011" => "south kabras",
            ],
            "207" => [
                "1012" => "butsotso east",
                "1013" => "butsotso south",
                "1014" => "butsotso central",
                "1015" => "sheywe",
                "1016" => "mahiakalo",
                "1017" => "shirere",
            ],
            "208" => [
                "1018" => "ingostse-mathia",
                "1019" => "shinoyi-shikomari-",
                "1020" => "bunyala west",
                "1021" => "bunyala east",
                "1022" => "bunyala central",
            ],
            "209" => [
                "1023" => "mumias central",
                "1024" => "mumias north",
                "1025" => "etenje",
                "1026" => "musanda",
                "1027" => "lubinu/lusheya",
                "1028" => "isongo/makunga/malaha",
                "1029" => "east wanga",
            ],
            "210" => [
                "1030" => "koyonzo",
                "1031" => "kholera",
                "1032" => "khalaba",
                "1033" => "mayoni",
                "1034" => "namamali",
            ],
            "211" => [
                "1035" => "marama west",
                "1036" => "marama central",
                "1037" => "marenyo - shianda",
                "1038" => "marama north",
                "1039" => "marama south",
            ],
            "212" => [
                "1040" => "kisa north",
                "1041" => "kisa east",
                "1042" => "kisa west",
                "1043" => "kisa central",
            ],
            "213" => [
                "1045" => "isukha north",
                "1046" => "murhanda",
                "1047" => "isukha central",
                "1048" => "isukha south",
                "1049" => "isukha east",
                "1050" => "isukha west",
            ],
            "214" => [
                "1051" => "idakho south",
                "1052" => "idakho east",
                "1053" => "idakho north",
                "1054" => "idakho central",
            ],
            "215" => [
                "1055" => "lugaga-wamuluma",
                "1056" => "south maragoli",
                "1057" => "central maragoli",
                "1058" => "mungoma",
            ],
            "216" => [
                "1059" => "lyaduywa/izava",
                "1060" => "west sabatia",
                "1061" => "chavakali",
                "1062" => "north maragoli",
                "1063" => "wodanga",
                "1064" => "busali",
            ],
            "217" => [
                "1065" => "shiru",
                "1066" => "muhudu",
                "1067" => "shamakhokho",
                "1068" => "gisambai",
                "1069" => "banja",
                "1070" => "tambua",
                "1071" => "jepkoyai",
            ],
            "218" => [
                "1072" => "luanda township",
                "1073" => "wemilabi",
                "1074" => "mwibona",
                "1075" => "luanda south",
                "1076" => "emabungo",
            ],
            "219" => [
                "1077" => "north east bunyore",
                "1078" => "central bunyore",
                "1079" => "west bunyore",
            ],
            "220" => [
                "1080" => "cheptais",
                "1081" => "chesikaki",
                "1082" => "chepyuk",
                "1083" => "kapkateny",
                "1084" => "kaptama",
                "1085" => "elgon",
            ],
            "221" => [
                "1086" => "namwela",
                "1087" => "malakisi/south kulisiru",
                "1088" => "lwandanyi",
            ],
            "222" => [
                "1087" => "kabuchai/chwele",
                "1088" => "west nalondo",
                "1089" => "bwake/luuya",
                "1090" => "mukuyuni",
            ],
            "223" => [
                "1091" => "south bukusu",
                "1092" => "bumula",
                "1093" => "khasoko",
                "1094" => "kabula",
                "1095" => "kimaeti",
                "1096" => "west bukusu",
                "1097" => "siboti",
            ],
            "224" => [
                "1098" => "bukembe west",
                "1099" => "bukembe east",
                "1100" => "township",
                "1101" => "khalaba",
                "1102" => "musikoma",
                "1103" => "east sang'alo",
                "1104" => "marakaru/tuuti",
                "1105" => "sang'alo west",
            ],
            "225" => [
                "1106" => "mihuu",
                "1107" => "ndivisi",
                "1108" => "maraka",
                "1109" => "misikhu",
                "1110" => "sitikho",
                "1111" => "matulo",
                "1112" => "bokoli",
            ],
            "226" => [
                "1113" => "kimilili",
                "1114" => "kibingei",
                "1115" => "maeni",
                "1116" => "kamukuywa",
            ],
            "227" => [
                "1117" => "mbakalo",
                "1118" => "naitiri/kabuyefwe",
                "1119" => "milima",
                "1120" => "ndalu/ tabani",
                "1121" => "tongaren",
                "1122" => "soysambu/ mitua",
            ],
            "228" => [
                "1123" => "malaba central",
                "1124" => "malaba north",
                "1125" => "ang'urai south",
                "1126" => "ang'urai north",
                "1127" => "ang'urai east",
                "1128" => "malaba south",
            ],
            "229" => [
                "1129" => "ang'orom",
                "1130" => "chakol south",
                "1131" => "chakol north",
                "1132" => "amukura west",
                "1133" => "amukura east",
                "1134" => "amukura central",
            ],
            "230" => [
                "1135" => "nambale township",
                "1136" => "bukhayo north/waltsi",
                "1137" => "bukhayo east",
                "1138" => "bukhayo central",
            ],
            "231" => [
                "1139" => "bukhayo west",
                "1140" => "mayenje",
                "1141" => "matayos south",
                "1142" => "busibwabo",
                "1143" => "burumba",
            ],
            "232" => [
                "1144" => "marachi west",
                "1145" => "kingandole",
                "1146" => "marachi central",
                "1147" => "marachi east",
                "1148" => "marachi north",
                "1149" => "elugulu",
            ],
            "233" => [
                "1150" => "namboboto nambuku",
                "1151" => "nangina",
                "1152" => "ageng'a nanguba",
                "1153" => "bwiri",
            ],
            "234" => [
                "1154" => "bunyala central",
                "1155" => "bunyala north",
                "1156" => "bunyala west",
                "1157" => "bunyala south",
            ],
            "235" => [
                "1158" => "west ugenya",
                "1159" => "ukwala",
                "1160" => "north ugenya",
                "1161" => "east ugenya",
            ],
            "236" => [
                "1162" => "sidindi",
                "1163" => "sigomere",
                "1164" => "ugunja",
            ],
            "237" => [
                "1165" => "usonga",
                "1166" => "west alego",
                "1167" => "central alego",
                "1168" => "siaya township",
                "1169" => "north alego",
                "1170" => "south east alego",
            ],
            "238" => [
                "1171" => "north gem",
                "1172" => "west gem",
                "1173" => "central gem",
                "1174" => "yala township",
                "1175" => "east gem",
                "1176" => "south gem",
            ],
            "239" => [
                "1177" => "west yimbo",
                "1178" => "central sakwa",
                "1179" => "south sakwa",
                "1180" => "yimbo east",
                "1181" => "west sakwa",
                "1182" => "north sakwa",
            ],
            "240" => [
                "1183" => "east asembo",
                "1184" => "west asembo",
                "1185" => "north uyoma",
                "1186" => "south uyoma",
                "1187" => "west uyoma",
            ],
            "241" => [
                "1188" => "kajulu",
                "1189" => "kolwa east",
                "1190" => "manyatta 'b'",
                "1191" => "nyalenda 'a'",
                "1192" => "kolwa central",
            ],
            "242" => [
                "1193" => "south west kisumu",
                "1194" => "central kisumu",
                "1195" => "kisumu north",
                "1196" => "west kisumu",
                "1197" => "north west kisumu",
            ],
            "243" => [
                "1198" => "railways",
                "1199" => "migosi",
                "1200" => "shaurimoyo kaloleni",
                "1201" => "market milimani",
                "1202" => "kondele",
                "1203" => "nyalenda b",
            ],
            "244" => [
                "1204" => "west seme",
                "1205" => "central seme",
                "1206" => "east seme",
                "1207" => "north seme",
            ],
            "245" => [
                "1208" => "east kano/wawidhi",
                "1209" => "awasi/onjiko",
                "1210" => "ahero",
                "1211" => "kabonyo/kanyagwal",
                "1212" => "kobura",
            ],
            "246" => [
                "1213" => "miwani",
                "1214" => "ombeyi",
                "1215" => "masogo/nyang'oma",
                "1216" => "chemelil",
                "1217" => "muhoroni/koru",
            ],
            "247" => [
                "1218" => "south west nyakach",
                "1219" => "north nyakach",
                "1220" => "central nyakach",
                "1221" => "west nyakach",
                "1222" => "south east nyakach",
            ],
            "248" => [
                "1223" => "west kasipul",
                "1224" => "south kasipul",
                "1225" => "central kasipul",
                "1226" => "east kamagak",
                "1227" => "west kamagak",
            ],
            "249" => [
                "1228" => "kabondo east",
                "1229" => "kabondo west",
                "1230" => "kokwanyo/kakelo",
                "1231" => "kojwach",
            ],
            "250" => [
                "1232" => "west karachuonyo",
                "1233" => "north karachuonyo",
                "1234" => "central",
                "1235" => "kanyaluo",
                "1236" => "kibiri",
                "1237" => "wangchieng",
                "1238" => "kendu bay town",
            ],
            "251" => [
                "1239" => "west gem",
                "1240" => "east gem",
                "1241" => "kagan",
                "1242" => "kochia",
            ],
            "252" => [
                "1243" => "homa bay central",
                "1244" => "homa bay arujo",
                "1245" => "homa bay west",
                "1246" => "homa bay east",
            ],
            "253" => [
                "1247" => "kwabwai",
                "1248" => "kanyadoto",
                "1249" => "kanyikela",
                "1250" => "north kabuoch",
                "1251" => "kabuoch south/pala",
                "1252" => "kanyamwa kologi",
                "1253" => "kanyamwa kosewe",
            ],
            "254" => [
                "1254" => "mfangano island",
                "1255" => "rusinga island",
                "1256" => "kasgunga",
                "1257" => "gembe",
                "1258" => "lambwe",
            ],
            "255" => [
                "1259" => "gwassi south",
                "1260" => "gwassi north",
                "1261" => "kaksingri west",
                "1262" => "ruma kaksingri east",
            ],
            "256" => [
                "1263" => "north kamagambo",
                "1264" => "central kamagambo",
                "1265" => "east kamagambo",
                "1266" => "south kamagambo",
            ],
            "257" => [
                "1267" => "north sakwa",
                "1268" => "south sakwa",
                "1269" => "west sakwa",
                "1270" => "central sakwa",
            ],
            "258" => [
                "1271" => "god jope",
                "1272" => "suna central",
                "1273" => "kakrao",
                "1274" => "kwa",
            ],
            "259" => [
                "1275" => "wiga",
                "1276" => "wasweta ii",
                "1277" => "ragana-oruba",
                "1278" => "wasimbete",
            ],
            "260" => [
                "1279" => "west kanyamkago",
                "1280" => "north kanyamkago",
                "1281" => "central kanyamkago",
                "1282" => "south kanyamkago",
                "1283" => "east kanyamkago",
            ],
            "261" => [
                "1284" => "kachien'g",
                "1285" => "kanyasa",
                "1286" => "north kadem",
                "1287" => "macalder/kanyarwanda",
                "1288" => "kaler",
                "1289" => "got kachola",
                "1290" => "muhuru",
            ],
            "262" => [
                "1291" => "bukira east",
                "1292" => "bukira centrl/ikerege",
                "1293" => "isibania",
                "1294" => "makerero",
                "1295" => "masaba",
                "1296" => "tagare",
                "1297" => "nyamosense/komosoko",
            ],
            "263" => [
                "1298" => "gokeharaka/getambwega",
                "1299" => "ntimaru west",
                "1300" => "ntimaru east",
                "1301" => "nyabasi east",
                "1302" => "nyabasi west",
            ],
            "264" => [
                "1303" => "bomariba",
                "1304" => "bogiakumu",
                "1305" => "bomorenda",
                "1306" => "riana",
            ],
            "265" => [
                "1307" => "tabaka",
                "1308" => "boikang'a",
                "1309" => "bogetenga",
                "1310" => "borabu / chitago",
                "1311" => "moticho",
                "1312" => "getenga",
            ],
            "266" => [
                "1313" => "bombaba borabu",
                "1314" => "boochi borabu",
                "1315" => "bokimonge",
                "1316" => "magenche",
            ],
            "267" => [
                "1317" => "masige west",
                "1318" => "masige east",
                "1319" => "bobasi central",
                "1320" => "nyacheki",
                "1321" => "bobasi bogetaorio",
                "1322" => "bobasi chache",
                "1323" => "sameta/mokwerero",
                "1324" => "bobasi boitangare",
            ],
            "268" => [
                "1325" => "majoge",
                "1326" => "boochi/tendere",
                "1327" => "bosoti/sengera",
            ],
            "269" => [
                "1328" => "ichuni",
                "1329" => "nyamasibi",
                "1330" => "masimba",
                "1331" => "gesusu",
                "1332" => "kiamokama",
            ],
            "270" => [
                "1333" => "bobaracho",
                "1334" => "kisii central",
                "1335" => "keumbu",
                "1336" => "kiogoro",
                "1337" => "birongo",
                "1338" => "ibeno",
            ],
            "271" => [
                "1339" => "monyerero",
                "1340" => "sensi",
                "1341" => "marani",
                "1342" => "kegogi",
            ],
            "272" => [
                "1343" => "bogusero",
                "1344" => "bogeka",
                "1345" => "nyakoe",
                "1346" => "kitutu   central",
                "1347" => "nyatieko",
            ],
            "273" => [
                "1348" => "rigoma",
                "1349" => "gachuba",
                "1350" => "kemera",
                "1351" => "magombo",
                "1352" => "manga",
                "1353" => "gesima",
            ],
            "274" => [
                "1354" => "nyamaiya",
                "1355" => "bogichora",
                "1356" => "bosamaro",
                "1357" => "bonyamatuta",
                "1358" => "township",
            ],
            "275" => [
                "1359" => "itibo",
                "1360" => "bomwagamo",
                "1361" => "bokeira",
                "1362" => "magwagwa",
                "1363" => "ekerenyo",
            ],
            "276" => [
                "1364" => "mekenene",
                "1365" => "kiabonyoru",
                "1366" => "nyansiongo",
                "1367" => "esise",
            ],
            "277" => [
                "1368" => "kitisuru",
                "1369" => "parklands/highridge",
                "1370" => "karura",
                "1371" => "kangemi",
                "1372" => "mountain view",
            ],
            "278" => [
                "1373" => "kilimani",
                "1374" => "kawangware",
                "1375" => "gatina",
                "1376" => "kileleshwa",
                "1377" => "kabiro",
            ],
            "279" => [
                "1378" => "mutuini",
                "1379" => "ngando",
                "1380" => "riruta",
                "1381" => "uthiru/ruthimitu",
                "1382" => "waithaka",
            ],
            "280" => [
                "1383" => "karen",
                "1384" => "nairobi west",
                "1385" => "mugumo-ini",
                "1386" => "south-c",
                "1387" => "nyayo highrise",
            ],
            "281" => [
                "1388" => "laini saba",
                "1389" => "lindi",
                "1390" => "makina",
                "1391" => "woodley/kenyatta golf",
                "1392" => "sarangombe",
            ],
            "282" => [
                "1393" => "githurai",
                "1394" => "kahawa west",
                "1395" => "zimmerman",
                "1396" => "roysambu",
                "1397" => "kahawa",
            ],
            "283" => [
                "1398" => "claycity",
                "1399" => "mwiki",
                "1400" => "kasarani",
                "1401" => "njiru",
                "1402" => "ruai",
            ],
            "284" => [
                "1403" => "baba dogo",
                "1404" => "utalii",
                "1405" => "mathare north",
                "1406" => "lucky summer",
                "1407" => "korogocho",
            ],
            "285" => [
                "1408" => "imara daima",
                "1409" => "kwa njenga",
                "1410" => "kwa reuben",
                "1411" => "pipeline",
                "1412" => "kware",
            ],
            "286" => [
                "1413" => "kariobangi north",
                "1414" => "dandora area i",
                "1415" => "dandora area ii",
                "1416" => "dandora area iii",
                "1417" => "dandora area iv",
            ],
            "287" => [
                "1418" => "kayole north",
                "1419" => "kayole central",
                "1420" => "kayole south",
                "1421" => "komarock",
                "1422" => "matopeni",
            ],
            "288" => [
                "1423" => "upper savannah",
                "1424" => "lower savannah",
                "1425" => "embakasi",
                "1426" => "utawala",
                "1427" => "mihango",
            ],
            "289" => [
                "1428" => "umoja i",
                "1429" => "umoja ii",
                "1430" => "mowlem",
                "1431" => "kariobangi south",
            ],
            "290" => [
                "1432" => "makongeni",
                "1433" => "maringo/hamza",
                "1434" => "harambee",
                "1435" => "viwandani",
            ],
            "291" => [
                "1436" => "pumwani",
                "1437" => "eastleigh north",
                "1438" => "eastleigh south",
                "1439" => "airbase",
                "1440" => "california",
            ],
            "292" => [
                "1441" => "nairobi central",
                "1442" => "ngara",
                "1443" => "ziwani/kariokor",
                "1444" => "pangani",
                "1445" => "landimawe",
                "1446" => "nairobi south",
            ],
            "293" => [
                "1447" => "hospital",
                "1448" => "mabatini",
                "1449" => "huruma",
                "1450" => "ngei",
                "1451" => "mlango kubwa",
                "1452" => "kiamaiko"
            ]
        ];
    }
}
